carreras={
    "D": [
        "Administración",
        "Administración de Turismo",
        "Administración de Negocios Internacionales",
        "Contabilidad",
        "Gestión Tributaria",
        "Auditoría Empresarial y del Sector Público",
        "Presupuesto y Finanzas Públicas",
        "Economía",
        "Economía Pública",
        "Economía Internacional"
    ],
    "A": [
        "Medicina Humana",
        "Obstetricia",
        "Enfermería",
        "Laboratorio Clínico",
        "Terapia Física y Rehabilitación",
        "Radiología",
        "Terapia Ocupacional",
        "Nutrición",
        "Farmacia y Bioquímica",
        "Ciencias de los Alimentos",
        "Toxicología",
        "Odontología",
        "Medicina Veterinaria",
        "Psicología",
        "Psicología Organizacional y de la Gestión Humana"
    ],
    "B": [
        "Química",
        "Ciencias Biológicas",
        "Genética y Biotecnología",
        "Microbiología y Parasitología",
        "Física",
        "Matemática",
        "Estadística",
        "Investigación Operativa",
        "Computación Científica"
    ],
    "C": [
        "Ingeniería Química",
        "Ingeniería Agroindustrial",
        "Ingeniería Mecánica de Fluidos",
        "Ingeniería Geológica",
        "Ingeniería Geográfica",
        "Ingeniería de Minas",
        "Ingeniería Metalúrgica",
        "Ingeniería Civil",
        "Ingeniería Ambiental",
        "Ingeniería Industrial",
        "Ingeniería Textil y Confecciones",
        "Ingeniería de Seguridad y Salud en el Trabajo",
        "Ingeniería Electrónica",
        "Ingeniería Eléctrica",
        "Ingeniería de Telecomunicaciones",
        "Ingeniería Biomédica",
        "Ingeniería de Sistemas",
        "Ingeniería de Software"
    ],
    "E": ['Derecho', 
            'Ciencia Política', 
            'Literatura', 
            'Filosofía', 
            'Lingüística', 
            'Comunicación Social', 
            'Arte', 'Bibliotecología y Ciencias de la Información',
            'Danza', 'Conservación y Restauración',
            'Educación Inicial', 'Educación Primaria', 
            'Educación Secundaria', 'Educación Física',
            'Historia', 'Sociología', 'Antropología',
            'Arqueología', 'Trabajo Social',
            'Geografía']

}